# Generated by Django 3.0.7 on 2020-06-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='privacy',
            field=models.BooleanField(default='False'),
            preserve_default=False,
        ),
    ]
