# Generated by Django 3.0.7 on 2020-06-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail', '0002_file_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
